version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: bank_nosql_db
    ports:
      - "27017:27017"
    volumes:
      - bank_mongo_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bank_backend_api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://database:27017/bank-db
    volumes:
      - ./client:/usr/src/client 
    depends_on:
      - database

volumes:
  bank_mongo_data: